### ISSUE TITLE
project_dir parameter being ignored ?

### ISSUE THREAD

**Issue by juanluisbaptiste** [geo-data/ansible-rancher-compose#1]
Hi,

I'm testing this module on ansible 2.2 with rancher-compose 0.8.6, with the following task:

```
- name: Start private docker registry using rancher-compose
  rancher_compose:
    project_dir: "/code/registry/"
    project_name: "{{ rancher_compose_project_name }}"
    docker_compose: "docker-compose-rancher.yml"
    url: "http://rancher.xxxx.com:8080"
    access_key: "{{ rancher_compose_access_key }}"
    secret_key: "{{ rancher_compose_secret_key }}"
    executable: "/usr/local/bin/rancher-compose"
    state: present

```

And the task fails with the following error:

```
fatal: [rancher.ctecsas.com]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/local/bin/rancher-compose --file docker-compose-rancher.yml --project-name registry --url http://rancher.xxxxx.com:8080 --access-key VALUE_SPECIFIED_IN_NO_LOG_PARAMETER --secret-key VALUE_SPECIFIED_IN_NO_LOG_PARAMETER create", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "access_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "docker_compose": "docker-compose-rancher.yml", 
            "env_file": null, 
            "executable": "/usr/local/bin/rancher-compose", 
            "project_dir": "/code/registry/", 
            "project_name": "registry", 
            "rancher_compose": null, 
            "secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "url": "http://rancher.xxxx.com:8080"
        }, 
        "module_name": "rancher_compose"
    }, 
    "msg": "[Errno 2] No such file or directory", 
    "rc": 2
}
```

It seems that the module can't find the docker-compose file or I'm doing something wrong ?
